service_ansible_dir: "services/{{ inventory_hostname }}"
service_custom_vars: "{{ service_ansible_dir }}/vars.yml"
service_subservices: "{{ service_ansible_dir }}/subservices.yml"
service_custom_tasks: "{{ service_ansible_dir }}/tasks.yml"
service_custom_nginx_conf: "{{ service_ansible_dir }}/nginx.conf"
service_data_dir: "{{ services_data_dir }}/{{ inventory_hostname }}"
service_private_dir: "{{ private_dir }}/{{ inventory_hostname }}"
service_nginx_dir: "{{ service_data_dir }}/etc/nginx"
service_server_name: "{{ inventory_hostname }}.{{ domain }}"
service_container_address: "{{ inventory_hostname }}_"
